### ISSUE TITLE
Http request from column of urls

### ISSUE THREAD

**Issue by trxe** [cap-sized/capport#49]
```yml
---
df_from: URLS
df_to: DATA
url_column: url
format: JSON # optional, case insensitive, default to JSON
method: GET # optional, case insensitive, default to GET
```
