### ISSUE TITLE
http request build column into one url with many params, with option to batch

### ISSUE THREAD

**Issue by trxe** [cap-sized/capport#50]
```yml
---
df_from: URLS
df_to: DATA

# url_column: url # NOW OPTIONAL, omission will default to use of query_params
format: JSON # optional, case insensitive, default to JSON
method: GET # optional, case insensitive, default to GET
# new args below
root: "https://api-web.nhle.com/v1/meta" 
# to construct "?players=8478402&teams=EDM,TOR", make sure the df URLS has the column "players" and "teams"
params: [ players, teams ]
extract: players@0.currentTeams # select field. currently no support for indexing yet

```

Default behaviour with `url_column` present: async reqwest for json from multiple urls, 
with the new behaviour collapsing all these into one url
