### ISSUE TITLE
Add SQLTransform

### ISSUE THREAD

**Issue by trxe** [cap-sized/capport#71]
https://docs.pola.rs/api/rust/dev/polars_sql/index.html

Need a SQLTransform to operate on frames with SQL directly. Should be a transform

example:
```yml
pipeline:
  http_single_request:
    # all your existing stuff
    - ...
    - label: transform_shift_chart
      task: transform
      args:
        name: data_total_unpack
        input: SHIFT_CHART_DF
        save_df: SHIFT_CHART_DF


transform:
  data_total_unpack:
    - sql: "SELECT data.* from self"
    - select:
        # id: csid # from the previous step
        # first_name: firstName.default # handle subpaths
        # last_name: lastName.default # handle subpaths
        # ...
    - drop:
        # ...
        # birth_state_province_name: True
```
