### ISSUE TITLE
Handle redundant right key on select fields

### ISSUE THREAD

**Issue by trxe** [cap-sized/capport#74]
Handle redundant right key on select fields, and add tests

```
    - join:
        join: PLAYER
        right_select:
          entityid: # equivalent to entityid: entityid
          firstname: 
          lastname: 
          age: 
        left_on: id
        right_on: entityid
        how: left
```
