### ISSUE TITLE
Pipeline Runner

### ISSUE THREAD

**Issue by trxe** [cap-sized/capport#80]
the last configurable to add.

- [ ] Change logger to use the timezone in `schedule` (can ignore the `every` node for now, but require it)
- [ ] selection of runner with run_with, selection of logger with `logger`

```yml
runner:
  logger: default
  run_with: sync_lazy # default, optional argument, also the only one that works now
  schedule:
    timezone: UTC # use this for logging
    # 1d or 1w or 10s or 2M (month) or 1Y or 10m30s
    every: Monday at 15:00 # internally parse to .every(Monday).at("15:00")
```
