### ISSUE TITLE
Draft outline of new framework

### ISSUE THREAD

**Issue by trxe** [cap-sized/capport#90]
## Todo

Remove all existing code (can copy later) and write new configs.

Update documentation fully.

Complete overhaul of existing framework.
We will now have only 3 types of tasks, and slightly different configurables

## Tasks
- source
  - different source tasks produce arrow that is converted into a Dataframe by the RootSource task
  - Dataframe is entered into the df universe ("database")
- transform
  - Remains the same except that it reads directly from the "database" without copying
  - RootTransform no longer copies out the main df
  - instead the first subtask reads from the db and releases before passing the new clone to the next
- sink
  - different sink tasks consume arrow that is copied out by the RootSink task

## Configurables

1. Model (for input/output shaping and validation)
2. **Connections** (new)
3. Transform
4. **Source** (new)
5. **Sink** (new)
6. Logger
7. Pipeline
8. Runner

### Transform/Source/Sink stages in pipeline

```yml
# source stage:
- label: yyyy
  stage: source
  task: name_of_source
  args:
    player_df: DF_A

# transform stage:
- label: xxxx
  stage: transform
  task: name_of_transform
  args:
    input: DF_A
    output: DF_B


# sink stage:
- label: zzzzB
  stage: sink
  task: name_of_sink_b
  args:
    name: name_of_sink_b
    input: DF_B


# another sink stage:
- label: zzzzA
  stage: sink
  task: name_of_sink_a
  args:
    name: name_of_sink_a
    input: DF_A
```

### Connection templates

Connections can be used by source/sinks. It is purely a template, it doesn't initiate its own clients unlike in the previous iteration of capport.

```yml
connections:
  default_postgres:
    uri_env_var: PG_URI_CAPPORT
    user_env_var: PG_USER_CAPPORT
    pw_env_var: PG_PW_CAPPORT
    db: csdb
```

### Source stage

```yml
source:
  players:
    use: default_postgres # on processing the pipeline, the `use` node is used to populate the other required variables (e.g. type, uri, user, pw)
    db: olddb # this overrides the default "db" in default_default
    query: "select * from players"
    
  player_full_info:
    type: http_single_request
    template: "https://api-web.nhle.com/v1/meta"
    params: 
       - input: $player_df
         param_column: player
         template: "players in {}" # defaults to "param={}"
         separator: " " # defaults to ","

   games_full_info:
     type: http_batch_request
     template: "https://api-web.nhle.com/v1/gamecenter/{}/landing"
     params: # does a cartesian product of the set of all columns of inputs if there are more than one blanks.
        - input: $game_df
          param_column: game_id
```

### Sink stage

```yml
sink: 
  players:
    use: default_postgres # on processing the pipeline, the `use` node is used to populate the other required variables (e.g. uri, user, pw)
    model: player
    
```
