### ISSUE TITLE
TransformTaskConfig

### ISSUE THREAD

**Issue by trxe** [cap-sized/capport#94]
```yml
label: transform_task_name
input: str_keyword_input
output: str_keyword_input
stages: Vec<YamlValue>
```
