### ISSUE TITLE
JoinTransformConfig

### ISSUE THREAD

**Issue by trxe** [cap-sized/capport#97]
```yml
join:
  left: str_keyword
  left_on: str_keyword
  left_prefix: str_keyword
  right: str_keyword
  right_on: str_keyword
  right_prefix: str_keyword
  how: jtype
```
